# Generated by Django 5.2.8 on 2025-12-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
